### ISSUE TITLE
请问代码中的source_fea.mat文件是对XD145经过iDTs特征提取和LLC编码后的特征吗？

### ISSUE THREAD

**Issue by xushichao2016** [XDYangLiu/CDFAG#2]
XD145总共有880个视频片段，source_fea.mat的维度是4000*600呢，不应该是4000*880吗？

**Comment by YangLiu9208** [comment]
为了和Infrared的600个红外视频对应，我们从XD145数据集随机挑选了600个视频用来训练。

**Comment by xushichao2016** [comment]
嗯嗯，谢谢！非常感谢！
