### ISSUE TITLE
请问平均识别率如何能达到论文中的75%左右呢？

### ISSUE THREAD

**Issue by xushichao2016** [XDYangLiu/CDFAG#3]
使用提供的默认配置，即S_train=40 ; T_train=25时，做了很多次测试，但是平均识别率均在69.5%左右，请问是需要修改哪些参数吗？如何能达到论文中的75%左右呢？非常非常感谢！

**Comment by YangLiu9208** [comment]
请尝试设置mu=0.1.

**Comment by xushichao2016** [comment]
修改该参数有效，非常感谢作者的回复！
