### ISSUE TITLE
dataset XD145 link does not work 

### ISSUE THREAD

**Issue by TheShasa** [XDYangLiu/CDFAG#4]
Hi, the link you shared for downloading the dataset XD145 does not work, can you tell use from where we can download it? 
Thank you

**Comment by YangLiu9208** [comment]
https://drive.google.com/drive/folders/0B1qfLiy9hTl6NUlHNFo1eFhzekU?resourcekey=0-NYGlSf0RU22IV2fS0lAh4Q&usp=share_link
